---
# Playbook for Jenkins Slave on Ubuntu 14.04 LTS

- hosts: jenkins_nodes
  remote_user: root
  roles:
    - plone.jenkins_node
    - gforcada.compile-python
  vars:
    python_26: true
    pillow: true
    lxml: true
