---
# Jenkins server to test jenkins.plone.org locally with vagrant

- hosts: master
  remote_user: vagrant
  roles:
    - plone.jenkins_server
  vars:
    admin_email: tisto@plone.org
    simple_theme_css_url: https://rawgit.com/plone/jenkins.plone.org/master/jenkins.plone.org.css
    simple_theme_js_url: https://cdnjs.cloudflare.com/ajax/libs/doony/2.1/js/doony.min.js
    jenkins_admins:
      - tisto
      - gforcada
      - svx
      - bloodbare
    github_orgs:
      - plone
      - collective
    node_names:
      - node
  vars_files:
    - secrets.yml

  tasks:
    # most probably this vagrant box will not have a public Internet IP
    # so it makes sense to disable security completely so you can play
    # without any problem
    - name: Disable login on jenkins
      sudo: yes
      replace: dest=/var/lib/jenkins/config.xml regexp='<useSecurity>true</useSecurity>' replace='<useSecurity>false</useSecurity>'
      notify:
      - 'Restart Jenkins'
      - 'restart nginx'

- hosts: node
  remote_user: vagrant
  roles:
    - plone.jenkins_node
