---
# Jenkins server for Plone CI testing

- hosts: test.jenkins.plone.org
  remote_user: root
  roles:
    - plone.jenkins_server

  tasks:
    # Install mr.roboto
    - name: Install nginx-extras
      apt: name=nginx-extras state=present
    - name: Checkout mr.roboto
      git: repo=https://github.com/plone/mr.roboto.git dest=/srv/mr.roboto
    - name: Run mr.roboto bootstrap
      shell: python2.7 bootstrap.py chdir=/srv/mr.roboto/
    - name: Run mr.roboto buildout
      shell: bin/buildout chdir=/srv/mr.roboto/
    - name: mr.roboto nginx sites-available
      template: src=etc/nginx/mrroboto dest=/etc/nginx/sites-available/mrroboto owner=root group=root mode=0755
    - name: mr.roboto nginx sites-enabled
      file: path=/etc/nginx/sites-enabled/mrroboto state=link src=/etc/nginx/sites-available/mrroboto
      notify: Restart nginx

  handlers:

    - name: Restart nginx
      action: service name=nginx state=restarted
