---
# Jenkins server to test jenkins.plone.org locally with vagrant

- hosts: master
  remote_user: vagrant
  roles:
    - plone.jenkins_server
  vars:
    admin_email: tisto@plone.org
    simple_theme_css_url: https://rawgit.com/plone/jenkins.plone.org/master/jenkins.plone.org.css
    simple_theme_js_url: https://cdnjs.cloudflare.com/ajax/libs/doony/2.1/js/doony.min.js
    jenkins_admins:
      - tisto
      - gforcada
      - svx
      - bloodbare
    github_orgs:
      - plone
      - collective
    node_names:
      - node
  vars_files:
    - secrets.yml

  tasks:
    # most probably this vagrant box will not have a public Internet IP
    # so it makes sense to disable security completely so you can play
    # without any problem
    - name: Disable login on jenkins
      sudo: yes
      replace: dest=/var/lib/jenkins/config.xml regexp='<useSecurity>true</useSecurity>' replace='<useSecurity>false</useSecurity>'
      notify:
      - 'Restart Jenkins'
      - 'restart nginx'

    - name: 'Override node configuration'
      sudo: yes
      copy:
        src=etc/node.xml
        dest=/var/lib/jenkins/nodes/node/config.xml
        owner=jenkins
        group=jenkins

    - name: 'Add dummy private key'
      sudo: yes
      copy:
        src=etc/vagrant.priv
        dest=/var/lib/jenkins/private_key
        owner=jenkins
        group=jenkins

    - name: 'Add credentials.xml'
      sudo: yes
      copy:
        src=etc/jenkins_credentials.xml
        dest=/var/lib/jenkins/credentials.xml
        owner=jenkins
        group=jenkins

- hosts: node
  remote_user: vagrant
  roles:
    - plone.jenkins_node

  tasks:
    # copy testing public key
    - name: 'Add dummy private key'
      sudo: yes
      authorized_key:
        user=jenkins
        key="{{ lookup('file', 'etc/vagrant.pub') }}"
