---
# Jenkins server for Plone CI testing

- hosts: jenkins.plone.org
  remote_user: root
  roles:
    - plone.jenkins_server
  vars_files:
    - jenkins_config.yml

  tasks:
    # Install mr.roboto
    - name: Install nginx-extras
      apt: name=nginx-extras state=present
    - name: Install supervisor
      pip: name=supervisor
    - name: Checkout mr.roboto
      git: repo=https://github.com/plone/mr.roboto.git dest=/srv/mr.roboto
    - name: Run mr.roboto bootstrap
      shell: python2.7 bootstrap.py chdir=/srv/mr.roboto/
    - name: Run mr.roboto buildout
      shell: bin/buildout chdir=/srv/mr.roboto/
      notify: Restart mr.roboto

  handlers:

    - name: Start mr.roboto
      supervisorctl: name=all state=started config=/srv/mr.roboto/supervisord.conf
    - name: Restart mr.roboto
      supervisorctl: name=all state=started config=/srv/mr.roboto/supervisord.conf
