---
# Jenkins server for Plone CI testing

- hosts: test.jenkins.plone.org
  remote_user: root
  roles:
    - plone.jenkins_server

  tasks:
    - name: Install nginx-extras
      apt: name=nginx-extras state=present
    - name: Checkout mr.roboto
      git: repo=https://github.com/plone/mr.roboto.git dest=/srv/mr.roboto
    - name: Run mr.roboto bootstrap
      shell: python2.7 bootstrap.py chdir=/srv/mr.roboto/
    - name: Run mr.roboto buildout
      shell: bin/buildout chdir=/srv/mr.roboto/
