---
# Jenkins server to test jenkins.plone.org locally with vagrant

- hosts: local
  remote_user: vagrant
  roles:
    - plone.jenkins_server
  vars_files:
    - jenkins_config.yml

  tasks:
    # most probably this vagrant box will not have a public Internet IP
    # so it makes sense to disable security completely so you can play
    # without any problem
    - name: Disable login on jenkins
      sudo: yes
      replace: dest=/var/lib/jenkins/config.xml regexp='<useSecurity>true</useSecurity>' replace='<useSecurity>false</useSecurity>'
      notify:
      - 'Restart Jenkins'
