# roles downloaded from galaxy.ansible.com
# (as we do not expect to be hacking on them)
- src: geerlingguy.java
  version: 1.9.6

- src: geerlingguy.jenkins
  version: 3.8.0

- src: geerlingguy.nodejs
  version: 6.0.0

- src: gforcada.compile_python
  version: 6.3.2

# roles downloaded from git as we expect to modify them
- src: https://github.com/plone/plone.jenkins_server
  version: master

- src: https://github.com/plone/plone.jenkins_node
  version: master
