---
# Jenkins server to test jenkins.plone.org locally with vagrant

# TODO(gforcada) remove it as soon as jenkins master is on Ubuntu 16.04
- hosts: master
  tasks:
    - name: Install repository for Java 8 in Ubuntu
      become: yes
      apt_repository: repo='ppa:openjdk-r/ppa'
    - name: Update
      become: yes
      apt:
        update_cache=yes
    - name: Install Java 8
      become: yes
      apt:
        name=openjdk-8-jdk
        state=installed
    - name: Fix java version selected
      become: yes
      alternatives:
        name: java
        path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

- hosts: master
  remote_user: vagrant
  become: yes
  roles:
    - plone.jenkins_server
  vars:
    admin_email: tisto@plone.org
    simple_theme_css_url: https://rawgit.com/plone/jenkins.plone.org/master/jenkins.plone.org.css
    simple_theme_js_url: https://cdnjs.cloudflare.com/ajax/libs/doony/2.1/js/doony.min.js
    jenkins_admins:
      - tisto
      - gforcada
      - svx
      - bloodbare
    github_orgs:
      - plone
      - collective
    nodes_info:
      - name: node
        host: "127.0.0.1"
        port: "8085"
    python_26: true
    pillow: true
    lxml: true
  vars_files:
    - ../secrets.yml

  tasks:
    # most probably this vagrant box will not have a public Internet IP
    # so it makes sense to disable security completely so you can play
    # without any problem
    - name: Disable login on jenkins
      become: yes
      replace: dest=/var/lib/jenkins/config.xml regexp='<useSecurity>true</useSecurity>' replace='<useSecurity>false</useSecurity>'
      notify:
      - 'restart jenkins'
      - 'restart nginx'

    - name: 'Override node configuration'
      become: yes
      copy:
        src=files/node.xml
        dest=/var/lib/jenkins/nodes/node/config.xml
        owner=jenkins
        group=jenkins

    - name: 'Add dummy private key'
      become: yes
      copy:
        src=files/key.priv
        dest=/var/lib/jenkins/private_key
        owner=jenkins
        group=jenkins

    - name: 'Add credentials.xml'
      become: yes
      copy:
        src=files/credentials.xml
        dest=/var/lib/jenkins/credentials.xml
        owner=jenkins
        group=jenkins

- hosts: node
  remote_user: vagrant
  become: yes
  roles:
    - plone.jenkins_node

  tasks:
    # copy testing public key
    - name: 'Add dummy private key'
      become: yes
      authorized_key:
        user=jenkins
        key="{{ lookup('file', 'files/key.pub') }}"
